version: '3.8'

services:
  # PHP 8.3 Service
  php:
    build:
      context: .
      dockerfile: ./dockerfiles/php.Dockerfile
    container_name: php_app
    volumes:
      - ./backend:/var/www
    env_file:
      - env/php.env
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_db
    env_file:
      - env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # Vue.js (Node.js) Service
  node:
    image: node:latest
    container_name: node_service
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
    command: ["npm", "run", "serve"]
    ports:
      - "8080:8080"
    networks:
      - app_network
  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_service
    env_file:
      - env/phpmyadmin.env
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - app_network
# Volumes
volumes:
  mysql_data:

# Networks
networks:
  app_network:
    driver: bridge
