version: '3.8'

services:
  # PHP-FPM Service for Laravel Backend
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend/src:/var/www
      - ./backend/config/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - app_network
    depends_on:
      - mysql

  # Nginx Service for Backend
  web:
    image: nginx:alpine
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # Composer Service for Laravel Backend
  composer:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: composer_service
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app_network
    command: ["composer", "install"]

  # Custom npm Service for Vue.js and Vuetify Frontend
  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: node_service
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
    networks:
      - app_network
    command: ["npm", "run", "dev"]

# Volumes
volumes:
  mysql_data:

# Networks
networks:
  app_network:
    driver: bridge
